### PR TITLE
Update Scala Native and remove no more needed Stubs

### PR DESCRIPTION
**Pull request by lolgab**
- Update Scala Native to latest 0.3.9 version
- Added ability to look at environment variables for Scala JS and Native milestones
- Removed Future, ExecutionContext, Promise, Await stubs, now they are supported
- Added an ExecutionContext for Scala Native which executes tasks synchronously cause SN doesn't support Await

### CODE REVIEW

**Comment by alexandru** [comment]
@lolgab this is very cool, thanks

**Comment by alexandru** [comment]
@lolgab getting an error on CircleCI, any ideas?

https://circleci.com/gh/monix/minitest/30?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by lolgab** [comment]
Can you try to rerun the job? If it doesn't disappear I'll give a look today.

**Comment by SethTisue** [comment]
I think something went wrong here. if I do `lawsLegacyJVM/publishLocal`, the resulting JAR has no classfiles in it

before:

```
~/minitest % jar tf /Users/tisue/.ivy2/local/io.monix/minitest-laws-legacy_2.12/2.5.0/jars/minitest-laws-legacy_2.12.jar
META-INF/MANIFEST.MF
minitest/
minitest/laws/
minitest/laws/Checkers.class
```

after:

```
~/minitest % jar tf /Users/tisue/.ivy2/local/io.monix/minitest-laws-legacy_2.12/2.5.0-eaa7377/jars/minitest-laws-legacy_2.12.jar
META-INF/MANIFEST.MF
```

I discovered this because it broke monix downstream in the Scala 2.12 community build

**Comment by alexandru** [comment]
I released a new version and I might have corrected the build failure.

@SethTisue the issue you've mentioned should be fixed now.

**Comment by SethTisue** [comment]
https://github.com/scala/community-builds/commit/a88016429e14e08d857273d03424fb730c558003 :+1:

**Pull request merged**
