### PR TITLE
Update to 2.13.0-M5

### LINKED ISSUE #23: publish for Scala 2.13.0-M5?
I think your dependencies are available for M4 now? (not 100% sure)

in the Scala 2.13 community build, at e.g. https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1228/consoleFull, I'm seeing that getting minitest onto the new collections would also help unlock a bunch of downstream projects. (most of which need cats too, but cats isn't too far from being able to publish, too.)

```
[info] Project ammonite--------------------: DID NOT RUN (stuck on broken dependencies: minitest, scala-async, spray-json, tut, utest)
[info] Project better-monadic-for----------: DID NOT RUN (stuck on broken dependencies: cats, minitest, pcplod)
[info] Project eff-------------------------: DID NOT RUN (stuck on broken dependencies: cats, minitest)
[info] Project fs2-reactive-streams--------: DID NOT RUN (stuck on broken dependencies: cats, minitest, scodec-bits, utest)
[info] Project giter8----------------------: DID NOT RUN (stuck on broken dependencies: cats, grizzled, minitest, scalamock, utest)
[info] Project http4s----------------------: DID NOT RUN (stuck on broken dependencies: cats, http4s-parboiled2, log4s, minitest, scodec-bits, spray-json, twirl, utest)
[info] Project kxbmap-configs--------------: DID NOT RUN (stuck on broken dependencies: cats, minitest, utest)
[info] Project minitest--------------------: FAILED (RuntimeException: )
[info] Project monix-----------------------: DID NOT RUN (stuck on broken dependencies: cats, minitest)
[info] Project sbinary---------------------: DID NOT RUN (stuck on broken dependencies: cats, minitest, utest)
[info] Project sbt-------------------------: DID NOT RUN (stuck on broken dependencies: cats, minitest, spray-json, utest)
[info] Project sbt-io----------------------: DID NOT RUN (stuck on broken dependencies: cats, minitest, utest)
[info] Project sbt-librarymanagement-------: DID NOT RUN (stuck on broken dependencies: cats, minitest, spray-json, utest)
[info] Project sbt-util--------------------: DID NOT RUN (stuck on broken dependencies: cats, minitest, spray-json, utest)
[info] Project scala-debugger--------------: DID NOT RUN (stuck on broken dependencies: minitest, scala-async, scalamock, scallop, spray-json, tut, utest)
[info] Project scala-ssh-------------------: DID NOT RUN (stuck on broken dependencies: cats, minitest, utest)
[info] Project scalafmt--------------------: DID NOT RUN (stuck on broken dependencies: cats, minitest, utest)
[info] Project scalaprops------------------: DID NOT RUN (stuck on broken dependencies: cats, minitest, utest)
[info] Project scopt-----------------------: DID NOT RUN (stuck on broken dependencies: minitest, utest)
[info] Project sttp------------------------: DID NOT RUN (stuck on broken dependencies: akka-actor, cats, minitest, scodec-bits, spray-json)
[info] Project zinc------------------------: DID NOT RUN (stuck on broken dependencies: cats, minitest, spray-json, utest)
```

### PR DESCRIPTION
**Pull request by ashawley**
The Scala.js build will fail because ScalaCheck isn't published, yet.

Fixes #23.

### CODE REVIEW

**Comment by ashawley** [comment]
Can the conditional in `build.sbt` for 2.13.0-M3 be deleted?

```scala
  needsScalaParadise := {
    val sv = scalaVersion.value
    (sv startsWith "2.10.") || (sv startsWith "2.11.") || (sv startsWith "2.12.") || (sv == "2.13.0-M3")
  },
```

**Comment by ashawley** [comment]
Compilation fails with:

```
bad option: '-Ywarn-inaccessible'
```

**Comment by ashawley** [comment]
Fails to get Scala.js,

```
unresolved dependency: org.scala-js#scalajs-library_2.13.0-M5;0.6.24: not found
```

But even after updating Scala.js, the build will still be stuck on ScalaCheck:

```
unresolved dependency: org.scalacheck#scalacheck_sjs0.6_2.13.0-M5;1.14.0: not found
```

Will remain in holding pattern for now.

**Comment by ashawley** [comment]
Fails to get Scala.js,

```
unresolved dependency: org.scala-js#scalajs-library_2.13.0-M5;0.6.24: not found
```

But even after updating Scala.js, the build will still be stuck on ScalaCheck:

```
unresolved dependency: org.scalacheck#scalacheck_sjs0.6_2.13.0-M5;1.14.0: not found
```

Will remain in holding pattern for now.

**Comment by ashawley** [comment]
This is ready to go. The tests are passing. It just needs a review.

**Comment by ashawley** [comment]
@SethTisue I'm new here, too.  You follow 2.13 changes, closely, so appreciate you weighing in.

**Comment by alexandru** [comment]
Thanks @ashawley

**Pull request merged**
