### PR TITLE
Upgrade to Scala 3.0.0-M2

### PR DESCRIPTION
**Pull request by smarter**

### CODE REVIEW

**Comment by Avasil** [comment]
Thank you:)

**Comment by Kevin-Lee** [comment]
Hi, is it also released? or will it be released anytime soon?

**Comment by Avasil** [comment]
@Kevin-Lee 

Not yet, I have some issues with my credentials setup on my work laptop so it seems like I can't release now but I will be able to do it on Thursday/Friday

**Comment by Kevin-Lee** [comment]
@Avasil Thank you!

**Comment by Avasil** [comment]
@Kevin-Lee I have released `2.9.1` with 3.0.0-M2

**Comment by Kevin-Lee** [comment]
@Avasil That's great! Thank you!

**Pull request merged**
