### PR TITLE
clean up build

### PR DESCRIPTION
**Pull request by larsrh**
* updates sbt version
* removes old macro-compat dependencies
* removes unneeded sources

### CODE REVIEW

**Comment by alexandru** [comment]
Yikes, CircleCI changed, and I don't think we're to blame here, we should migrate to GitHub Actions.

**Comment by alexandru** [comment]
For now we should deactivate CircleCI.

**Comment by larsrh** [comment]
OK, I can try to file another PR that migrates to GitHub Actions, unless you want to do it yourself.

**Comment by alexandru** [comment]
> OK, I can try to file another PR that migrates to GitHub Actions, unless you want to do it yourself.

Sure, that would be awesome!

**Comment by larsrh** [comment]
Ready for merge @Avasil

**Pull request merged**
