### PR TITLE
Test Scala JS 1.0.0-RC2 and Scala Native 0.4.0-M2

### PR DESCRIPTION
**Pull request by lolgab**
Supersedes #49

### CODE REVIEW

**Comment by mikla** [comment]
@alexandru please, review.

**Comment by SethTisue** [comment]
ping, could this perhaps get some maintainer attention...?

**Comment by SethTisue** [comment]
there's also #51  now

**Comment by alexandru** [comment]
Why doesn't this have a problem with ScalaCheck 1.13.x, the "legacy" support?

**Comment by alexandru** [comment]
@lolgab I've merged #51, can you please merge your changes, in order to update ScalaNative as well?

**Comment by alexandru** [comment]
I'll take a look soon if not, to unblock Scala.js 1.0

**Comment by lolgab** [comment]
> Why doesn't this have a problem with ScalaCheck 1.13.x, the "legacy" support?

Because I defined custom command aliases to avoid testing/publishing scalacheck legacy when Scala.js 1.0.x is used

**Comment by lolgab** [comment]
> @lolgab I've merged #51, can you please merge your changes, in order to update ScalaNative as well?

Sure I can!

**Comment by lolgab** [comment]
Scala Native 0.4.0-M2 is already published. Closing.

**Pull request closed without merging**
